### PR TITLE
Update for Grails 3.1.5

### PR DESCRIPTION
**Pull request by IteraSpeed**

### CODE REVIEW

**Comment by nilskuhn** [comment]
What about this? Do you plan to integrate this update to grails 3.1.x?
I would like to use the plugin within 3.1!

**Comment by nilskuhn** [comment]
Could you please accept our pr or comment what's missing?
We can't build our grails application [OpenSpeedMonitor](https://github.com/IteraSpeed/OpenSpeedMonitor) in our ci server cause of missing plugin :(

**Comment by sburnicki** [comment]
@graemerocher: Any comments about this? I would also love to see this upstream.

**Comment by nilskuhn** [comment]
*NICE*
Thanks a lot!

**Pull request merged**
